# Site settings
title: Insane Programming
header-img: img/home-bg.jpg
email: lievendoclo1983@gmail.com
copyright_name: Lieven Doclo
description: "Ramblings of a seasoned Java developer"
baseurl: ""
url: "http://www.insaneprogramming.be"
twitter_username: lievendoclo
github_username:  lievendoclo
facebook_username:  LievenDoclo
email_username:  lievendoclo1983@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
